config/routes.rb
module RailsShop
  # ::RailsShop::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::RailsShop::DefaultRoutes
      mapper.send :rails_shop_routes
    end
  end

  module DefaultRoutes
    def rails_shop_routes
      get 'shop_search' => "shop_search#shop_search"

      get 'products_search_a/:term' => "shop_search#ts_products_search"
      get 'products_search_b/:term' => "shop_search#psql_products_search"
      get 'products_search_c/:term' => "shop_search#psql_products_search2"

      get '/shop'       => 'products#index', as: :shop
      get 'shop/manage' => 'shop#manage',    as: :shop_manage

      get   'yandex_market/index'      => 'yandex_market#index',  as: :yandex_market
      patch 'yandex_market/switch/:id' => 'yandex_market#switch', as: :yandex_market_switch

      get   'yandex_market/export' => 'yandex_market#export', as: :yandex_market_export
      get   'yandex_market/export_this/:id' => 'yandex_market#export_this', as: :yandex_market_export_this

      resources :shop_params_cards

      resources :shop_categories do
        member do
          get :ordering
        end

        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_brands do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_colors do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_unit_ports do
        collection do
          get  :manage
          post :rebuild
        end
      end

      get "shop_ordering/:category_type/:category_id",
        action: :ordering,
        controller: :shop_category_rels,
        as: :shop_ordering

      resources :shop_category_rels do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :products do
        member do
          post  :clone
          patch :realtion_category
        end

        collection do
          get :manage
        end
      end

      # ADD/REMOVE PRODUCTS
      post   "add_to_cart/:product_id"      => "carts#add_product",    as: :add_to_cart
      delete "remove_from_cart/:product_id" => "carts#remove_product", as: :remove_from_cart

      resources :carts do
        member do
          delete :reset
          patch :set_delivery_type

          patch  :amount_decrement
          patch  :amount_increment
        end

        collection do
          get :manage
        end
      end

      resources :orders do
        member do
          get :payment_system
          get :login_before
          get :attach_current_user_to

          patch :recalc_price
          patch :completion
          get   :payment
        end

        collection do
          get :my
          get :search
          get :manage

          post :one_click
        end
      end

      resources :currency_rates do
        collection do
          get :cbr_get_rate
          get :manage
        end
      end

      resources :delivery_types do
        collection do
          get :manage
        end
      end

      # Yandex Kassa routes
      match 'payments/yk/check-url' => 'payments#yk_check',   via: %w[ get post ]
      match 'payments/yk/aviso-url' => 'payments#yk_aviso',   via: %w[ get post ]
      match 'payments/yk/success'   => 'payments#yk_success', via: %w[ get post ]
      match 'payments/yk/failure'   => 'payments#yk_failure', via: %w[ get post ]

      # Alfa Bank routes
      post 'alfa_payments' => 'payments#alfa_before'
      get  'alfa_callback' => 'payments#alfa_callback'
      get  'alfa_success'  => 'payments#alfa_success'
      get  'alfa_failure'  => 'payments#alfa_failure'

      ##########################
      # ~ SHOP
      ##########################
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  include ::SimpleSort::Base
  include ::Pagination::Base

  include ::RailsShop::PriceMethods

  voiceless { prepend ::AppViewEngine::Cart }

  def to_param; self.uid; end

  # expire time in hours
  EXPIRE_AFTER = 3 * 24

  belongs_to :user
  before_validation :build_uid, on: :create
  validates_presence_of :uid

  has_many :cart_items
  def items_relation; cart_items; end

  scope :empty,  -> { where     cart_items_counter: 0 }
  scope :filled, -> { where.not cart_items_counter: 0 }

  scope :active,  -> { where 'carts.created_at > ?', (Time.zone.now - ::Cart::EXPIRE_AFTER.hours) }
  scope :expired, -> { where 'carts.created_at < ?', (Time.zone.now - ::Cart::EXPIRE_AFTER.hours) }

  def active?
    created_at > (Time.zone.now - ::Cart::EXPIRE_AFTER.hours)
  end

  class << self
    def recalc_items_counter!
      all.each do |cart|
        cart.update_attribute(:cart_items_counter, cart.cart_items.count)
      end
    end

    def destroy_expired!
      empty.expired.destroy_all
    end
  end

  private

  def build_uid
    self.uid = Digest::MD5.hexdigest("#{ Time.now }-#{ rand }")[0...7].downcase
  end
end

app/controllers/carts_controller.rb
class CartsController < RailsShopController

  before_action :find_cart_by_cart_id, only: %w[
    add_product remove_product
  ]

  before_action :find_cart_by_id, only: %w[
    amount_decrement amount_increment
    set_delivery_type
  ]

  before_action :find_product, only: %w[
    add_product remove_product
    amount_decrement amount_increment
  ]

  before_action :authenticate_user!, except: %w[
    show
    set_delivery_type
    add_product remove_product
    amount_increment amount_decrement
    reset
  ]

  before_action :shop_admin_required!, except: %w[
    index show
    set_delivery_type
    add_product remove_product
    amount_increment amount_decrement
    reset destroy
  ]

  before_action :set_cart,       only: %w[ destroy ]
  before_action :owner_required, only: %w[ destroy ]

  # PUBLIC AREA

  def index
    @carts = current_user.carts.max2min(:created_at).simple_sort(params).pagination(params)
  end

  def show
    @cart = Cart.where(uid: params[:id]).first || @cart
  end

  def set_delivery_type
    if dt = DeliveryType.where(id: params[:delivery_type_id]).first
      @cart.cart_items.deliveries.destroy_all
      @cart.cart_items.create(item: dt)
      return redirect_to :back, notice: 'Изменен вариант доставки'
    end

    redirect_to :back, notice: 'Не удалось сменить варинт доставки'
  end

  def add_product
    @cart.cart_items.create(item: @product, amount: 1, price: @product.price)
    @cart.increment!(:cart_items_counter)

    ::CartService.add_default_delivery_if_need(@cart)
    ::RailsShopLogger.product_added_to_cart(@cart.id, @product.id)

    session[:product_added] = true

    redirect_to :back, notice: 'Товар помещен в корзину'
  end

  def remove_product
    @cart.cart_items.where(item: @product).destroy_all
    @cart.decrement!(:cart_items_counter)

    ::CartService.delete_cart_if_need(@cart, cookies)
    ::RailsShopLogger.product_removed_from_cart(@cart.id, @product.id)

    session[:product_removed] = true
    session[:product_removed_id] = @product.id

    redirect_to :back, notice: 'Товар удален из корзины'
  end

  def amount_increment
    cart_item = @cart.cart_items.where(item: @product).first

    if cart_item.amount < @product.amount
      session[:product_added] = true
      cart_item.update(amount: cart_item.amount.next)
      redirect_to :back, notice: 'Количество данного товара в корзине увеличено'
    else
      redirect_to :back, notice: 'Количество данного товара в корзине достигло максимального значения'
    end
  end

  def amount_decrement
    cart_item = @cart.cart_items.where(item: @product).first

    if cart_item.amount > 1
      session[:product_added] = true
      cart_item.update(amount: cart_item.amount.pred)
      redirect_to :back, notice: 'Количество данного товара в корзине уменьшено'
    else
      redirect_to :back, notice: 'Количество данного товара в корзине достигло минимального значения'
    end
  end

  def reset
    ::CartService.reset_current_cart(cookies)
    redirect_to shop_path, notice: 'Корзина очищена'
  end

  # RESTRICTED AREA

  def manage
    @carts = Cart.filled.max2min(:created_at).simple_sort(params).pagination(params)
  end

  def destroy
    @cart = Cart.find_by_uid params[:id]
    @cart.destroy
    redirect_to :back, notice: 'Корзина удалена'
  end

  private

  def set_cart
    @cart = Cart.find_by_uid params[:id]
    @owner_check_object = @cart
  end

  def find_cart_by_id
    @cart = ::CartService.define_cart(params[:id], current_user, cookies)
    page_404 unless @cart
  end

  def find_cart_by_cart_id
    @cart = ::CartService.define_cart(params[:cart_id], current_user, cookies)
    page_404 unless @cart
  end

  def find_product
    @product = Product.friendly_first(params[:product_id])
    page_404 unless @product
  end
end

app/controllers/concerns/rails_shop/alfa_bank_payments.rb
require 'net/http'

# TEST TEST
# 4111 1111 1111 1111
# 2019/12
# 123
# 3dsecure: 12345678

# Регистрация заказа  https://pay.alfabank.ru/payment/rest/register.do
# Регистрация заказа с предавторизацией   https://pay.alfabank.ru/payment/rest/registerPreAuth.do
# Запрос завершения оплаты заказа   https://pay.alfabank.ru/payment/rest/deposit.do
# Запрос отмены оплаты заказа   https://pay.alfabank.ru/payment/rest/reverse.do
# Запрос возврата средств оплаты заказа   https://pay.alfabank.ru/payment/rest/refund.do
# Получение статуса заказа  https://pay.alfabank.ru/payment/rest/getOrderStatus.do
# Получение расширенного статуса заказа   https://pay.alfabank.ru/payment/rest/getOrderStatusExtended.do
# Запрос проверки вовлеченности карты в 3DS     https://pay.alfabank.ru/payment/rest/verifyEnrollment.do
# Запрос статистики по платежам за период   https://pay.alfabank.ru/payment/rest/getLastOrdersForMerchants.do

# Название метода   URL WSDL
# Описание WebService (WSDL)  https://pay.alfabank.ru/payment/webservices/merchant-ws?wsdl

# Название метода   URL
# Личный кабинет  https://pay.alfabank.ru/mportal

# include RailsShop::AlfaBankPayments
module RailsShop
  module AlfaBankPayments
    extend ActiveSupport::Concern

    ALFA_GATEWAY_URL = Settings.rails_shop.alfa_payments.api.url      # https://pay.alfabank.ru/payment/rest/
    ALFA_RETURN_URL  = Settings.rails_shop.alfa_payments.api.callback # https://example.com/alfa_callback

    ALFA_API_USER = Settings.rails_shop.alfa_payments.api.login
    ALFA_API_PASS = Settings.rails_shop.alfa_payments.api.password

    ALFA_AUTH_DATA = { userName: ALFA_API_USER, password: ALFA_API_PASS }

    included do
      SHOP_PUBLIC_ACTIONS = %w[ alfa_before alfa_callback alfa_success alfa_failure ]
      layout 'rails_shop_frontend'

      skip_before_action :authenticate_user!,        only: SHOP_PUBLIC_ACTIONS
      skip_before_action :shop_admin_required!,      only: SHOP_PUBLIC_ACTIONS
      skip_before_action :verify_authenticity_token, only: SHOP_PUBLIC_ACTIONS
    end

    def alfa_before
      order_id = params[:orderNumber]
      price = (params[:sum].to_f * 100).to_i

      unless order_ready_check(order_id)
        redirect_to alfa_failure_path(id: order_id)
      end

      data = {
        amount: price,
        orderNumber: order_id,
        returnUrl: ALFA_RETURN_URL
      }

      res = alfa_gateway('register.do', data)

      begin
        AlfaLogMailer.log_params("Alfa Bank PrePay: #{ order_id }", {
          order: order_id,
          alfa_price: price,
          price_param: params[:sum],

          response: res,
          params: params,
          ssl: request.ssl?,
        }).deliver_now
      rescue; end

      if (alfa_bank_payment_page = res['formUrl']).present?
        redirect_to alfa_bank_payment_page
      else
        redirect_to alfa_failure_path(id: order_id)
      end
    end

    def alfa_callback
      # /alfa_callback?orderId=29742882-196c-4ef2-9517-4859f6933e41
      alfa_order_id = params[:orderId]
      data = { orderId: alfa_order_id }
      res = alfa_gateway('getOrderStatus.do', data)

      begin
        AlfaLogMailer.log_params("Alfa Bank Callback", {
          alfa_order_id: alfa_order_id,
          response: res,
          params: params,
          ssl:    request.ssl?
        }).deliver_now
      rescue; end

      if res['ErrorCode'] == '0'
        order_id = res['OrderNumber']

        @order = Order.where(uid: order_id).first
        @order.process_payment_complete!

        begin
          AlfaLogMailer.log_params("Alfa Bank - ЗАКАЗ ОПЛАЧЕН", {
            alfa_order_id: alfa_order_id,
            response: res,
            params: params,
            ssl:    request.ssl?
          }).deliver_now
        rescue; end

        redirect_to alfa_success_url(id: order_id)
      else

        begin
          AlfaLogMailer.log_params("Alfa Bank - ОШИБКА ОПЛАТЫ ЗАКАЗА", {
            alfa_order_id: alfa_order_id,
            response: res,
            params: params,
            ssl:    request.ssl?
          }).deliver_now
        rescue; end

        redirect_to alfa_failure_path(id: order_id)
      end
    end

    def alfa_success
      order_uid = params[:id].to_s.downcase
      @order = Order.where(uid: order_uid).first
    end

    def alfa_failure
      order_uid = params[:id].to_s.downcase
      @order = Order.where(uid: order_uid).first
    end

    private

    def order_ready_check order_number
      Order.where(uid: order_number).first.ready_for_sale?
    end

    def alfa_gateway(action, params = {})
      params = params.merge(ALFA_AUTH_DATA)
      uri = URI(ALFA_GATEWAY_URL + action)
      res = ::Net::HTTP.post_form(uri, params)
      JSON.parse(res.body)
    end
  end
end

app/controllers/concerns/rails_shop/category_common_controller.rb
# include RailsShop::MainImageActions
module RailsShop
  module CategoryCommonController
    extend ActiveSupport::Concern

    included do
      before_action :set_shop_category, only: %w[ show ]
      before_action :set_editable_shop_category, only: %w[ edit update destroy ]

      include ::TheSortableTreeController::Rebuild
    end # included

    def index
      # ???
    end

    def show
      @shop_category_rels =
        ::ShopCategoryRel.base_scope
          .where(category: @shop_category)

      @filter_types = @shop_category_rels
        .pluck(:item_shop_params_card_type)
        .uniq
        .compact

      @shop_category_rels =
        @shop_category_rels
          .includes(:item)
          .show_sorting(params)
          .pagination(params)

      @shop_items = @shop_category_rels.map(&:item)
      render category_template(:show)
    end

    # RESTRICTED AREA

    def manage
      @shop_categories = category_klass.for_manage.nested_set
      render category_template(:manage)
    end

    def new
      @shop_category = category_klass.new
      render category_template(:new)
    end

    def edit
      render category_template(:edit)
    end

    def create
      @shop_category = current_user.send(category_name).new(shop_category_params)

      if @shop_category.save
        redirect_to url_for([:edit, @shop_category]), notice: 'Категория успешно создан'
      else
        render category_template(:new)
      end
    end

    def update
      @shop_category.assign_attributes(shop_category_params)
      @shop_category.content_processing_for(current_user)

      if @shop_category.save
        redirect_to url_for([:edit, @shop_category]), notice: 'Категоря успешно обновлена'
      else
        render category_template(:edit)
      end
    end

    def destroy
      @shop_category.destroy
      redirect_to [:manage, @shop_category], notice: 'Раздел удален'
    end

    private

    def set_shop_category
      @shop_category = category_klass.available_for(current_user).friendly_first(params[:id])
      return page_404 unless @shop_category
    end

    def set_editable_shop_category
      @shop_category = category_klass.for_manage.friendly_first(params[:id])
      return page_404 unless @shop_category
    end

    def shop_category_params
      param_name = category_name.singularize

      params.require(param_name).permit(
        :title,
        :url,
        :raw_intro,
        :raw_content,
        :state
      )
    end

    def category_name
      category_klass.name.tableize
    end

    def category_template name
      { template: "rails_shop/#{ category_name }/#{ name }" }
    end
  end
end

app/controllers/concerns/rails_shop/main_image_actions.rb
# include RailsShop::MainImageActions
module RailsShop
  module MainImageActions

    ACTIONS = %w[
      main_image_crop_16x9
      main_image_crop_4x3
      main_image_crop_1x1
      main_image_rotate_left
      main_image_rotate_right
      main_image_delete
    ]

    def main_image_crop_16x9
      path = @main_image_holder.main_image_crop_16x9(params)
      render json: { ids: { '@main-image--v16x9' => path + rnd_num  } }
    end

    def main_image_crop_4x3
      path = @main_image_holder.main_image_crop_4x3(params)
      render json: { ids: { '@main-image--v4x3' => path + rnd_num } }
    end

    def main_image_crop_1x1
      path = @main_image_holder.main_image_crop_1x1(params)
      render json: { ids: { '@main-image--v1x1' => path + rnd_num } }
    end

    def main_image_rotate_left
      @main_image_holder.main_image_rotate_left
      redirect_to :back
    end

    def main_image_rotate_right
      @main_image_holder.main_image_rotate_right
      redirect_to :back
    end

    def main_image_delete
      @main_image_holder.main_image_destroy!
      redirect_to :back
    end

    private

    def rnd_num
      "?#{ Time.now.to_i }"
    end

  end # MainImageActions
end # RailsShop

app/views/rails_shop/carts/cart_btn.html.slim
- if try :current_cart
  = link_to cart_path(current_cart), class: 'ptz_btn ptz_size-15' do
    i.fa.fa-shopping-cart.ptz_btn--icon.mr10
    - products_count = current_cart.cart_items.products.count
    - products_plur  = t(:products_count_text, scope: %w[ rails_shop ], count: products_count)
    = t(:products_count, scope: %w[ rails_shop cart cart_btn ], count: current_cart.cart_items.products.count, products_plur: products_plur)
- else
  .ptz_btn.ptz_size-15
    i.fa.fa-shopping-cart.ptz_btn--icon.mr10
    = t(:blank, scope: %w[ rails_shop cart ])

app/views/rails_shop/carts/index.html.slim
= render partial: 'users/header_footer'

- content_for :left_sidebar do
  = render partial: 'users/left_sidebar'

.ml20
  table.table-light--table.w100p
    tr.table-light--tr
      th.table-light--th.fs15 Номер заказа
      th.table-light--th.fs15= link_to 'Позиций ↕', simple_sort_url(:cart_items_counter)
      th.table-light--th.fs15 Товары
      th.table-light--th.fs15 Статус
      th.table-light--th.fs15= link_to 'Дата создания ↕', simple_sort_url(:created_at)
      th.table-light--th

    - @carts.each do |cart|
      tr.table-light--tr
        td.table-light--td.vam
          = link_to cart.uid.upcase, cart, class: 'link--block fs15 pt0 lh120'
        td.table-light--td.vam
          .fs15= cart.cart_items_counter
        td.table-light--td.vam.w100p
          .fs15
            - cart.products.each do |product|
              - product = product.item
              = image_tag product.main_image_url(:v100x100), width: '30', title: product.title

        td.table-light--td.vam
          .fs15
            = cart.active? ? 'Активна' : 'Просрочена'
        td.table-light--td.vam
          .fs15= cart.created_at.strftime('%d.%m.%Y %H:%M')
        td.table-light--td.vam
          = link_to cart, method: :delete, data: { confirm: 'Удалить корзину?' } do
            i.fs14.fa.fa-trash

  = render template: 'common/paginator', locals: { items: @carts }

app/views/rails_shop/carts/manage.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- content_for :left_sidebar do
  .m20= render partial: 'users/left_sidebar'

.m20
  .mt20.mb20.fs14
    span.mr15= link_to 'Кабинет', cabinet_path
    span.mr15 &raquo;
    span.mr15 Корзины

  .ptz_theme-0
    table.ptz_table-0.w100p
      tr
        th.p10.fs15.br-off Номер заказа
        th.p10.fs15.br-off= link_to 'Позиций ↕', simple_sort_url(:cart_items_counter)
        th.p10.fs15.br-off.tal Товары
        th.p10.fs15.br-off= link_to 'Пользователь ↕', simple_sort_url(:user_id)
        th.p10.fs15.br-off= link_to 'Дата создания ↕', simple_sort_url(:created_at)
        th.p10

      - @carts.each do |cart|
        tr
          td.p10.vam.br-off
            = link_to cart.uid.upcase, cart, class: 'link--block fs15 pt0 lh120'
          td.p10.vam
            .fs15= cart.cart_items_counter
          td.p10.vam.w100p
            .fs15
              - cart.products.each do |product|
                - product = product.item
                = image_tag product.main_image_url(:v100x100), width: '30', title: product.title

          td.p10.vam
            .fs15= cart.user ? cart.user.login : '---'
          td.p10.vam
            .fs15= cart.created_at.strftime('%d.%m.%Y %H:%M')
          td.p10.vam
            = link_to cart, method: :delete, data: { confirm: 'Удалить корзину?' } do
              i.fs14.fa.fa-trash

  = render template: 'common/paginator', locals: { items: @carts }

app/views/rails_shop/carts/show.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- @main_content_block_class = 'shop-cart--background'

- if @cart.cart_items.products.empty?
  .shop-cart--empty
    .info-block--notice.p20
      .fs17
        p.b В вашей корзине еще нет товаров
        p
          | Однако, это легко исправить. Перейдите на
          '
          span.u= link_to 'главную страницу', shop_url
          '
          | магазина и подберите себе что-нибудь интересное и полезное

- else
  .order-process-steps.mt20
    .order-process-steps--item.current 1. Корзина
    .order-process-steps--item 2. Доставка
    .order-process-steps--item 3. Оплата

  .shop-cart
    ul.shop-cart--list
      li.shop-cart--title
        h3.fs24 Корзина

      li.shop-cart--headers
        .shop-cart--header Информация о товаре
        .shop-cart--header.w20p Количество
        .shop-cart--header.w15p Цена
        .shop-cart--header.w5p

      = render template: 'rails_shop/price_ru/added_to_cart'

      - @cart.cart_items.products.min2max(:created_at).each do |cart_item|
        - product = cart_item.item
        li.shop-cart--position
          .shop-cart--position-cell
            - img = product.main_image_url(:v100x100)
            .shop-cart--image(style="background-image:url(#{ img })")

            = link_to product.title, product, class: 'link--block shop-cart--product-name'
            .shop-cart--product-info
              = product.equipment

          .shop-cart--position-cell.w20p

            .mb10.br-off
              - minus_disabled = :disabled if cart_item.amount == 1
              = button_to amount_decrement_cart_path(@cart, product_id: product), method: :patch, disabled: minus_disabled, form_class: 'iblock amount-manager--form', class: 'ptz_btn ptz_size-14 ptz_btn--side-left w40 b' do
                |&ndash;

              = text_field_tag :count, cart_item.amount, maxlength: 1, min: 0, max: 9, readonly: :readonly, autocomplete: :off, class: 'ptz_input ptz_size-14 brn w40 tac'

              - plus_disabled = :disabled if product.amount < cart_item.amount.next
              = button_to amount_increment_cart_path(@cart, product_id: product), method: :patch, disabled: plus_disabled, form_class: 'iblock amount-manager--form', class: 'iblock  ptz_btn ptz_size-14 ptz_btn--side-right w40 b' do
                |+

            .mt10.fs13
              | На складе:
              '
              = product.amount

          .shop-cart--position-cell.w15p
             .shop-cart--position-price
                ruby:
                  price = product_price(product)
                  discounted_price = product_discounted_price(product)

                = money_to_text(discounted_price)
                - if price != discounted_price
                  '
                  span.s= money_to_text(price)

          .shop-cart--position-cell.w5p
            = link_to remove_from_cart_path(product, cart_id: @cart), method: :delete, class: 'link--block shop-cart--position-delete' do
              i.fa.fa-trash-o

      li.cart-delivery-info
        h3.fs18.mt15.mb15 Доставка:
        a name='delivery_form'
        = form_tag set_delivery_type_cart_path(@cart, anchor: :delivery_form), method: :patch, data: { role: 'delivery-type--form-options' } do
          - selected_dt = @cart.cart_items.deliveries.first.try(:item)
          - DeliveryType.published.order(price: :desc).each do |dt|
            .cart-delivery-info--radio-btn.fs15.mb20
              = radio_button_tag :delivery_type_id, dt.id, (selected_dt == dt), class: 'radio-btn radio-btn--info-line', id: "delivery_type_#{ dt.id }", autocomplete: :off
              '
              label.ml10(for="delivery_type_#{ dt.id }")
                - if dt.moderation_required?
                  span.b>
                    | [Требует уточнения цены оператором]
                - else
                  - if money_to_text(dt.price).to_i.zero?
                    span.b>
                      | [Бесплатно]
                  - else
                    span.b>= raw "#{ money_to_text dt.price } руб."

                span.iblock.mb10= dt.title
                br
                span.fs12.pl25.lh130= dt.intro

      li.shop-cart--total
        .ptz_table.w100p
          .ptz_tr
            .ptz_td
              .fs15.mt10.mb10
                - products_count = @cart.products.count
                - positions_plur = t(:positions_count_text, scope: %w[ rails_shop ], count: products_count)
                | #{ products_count } #{ positions_plur } на
                '
                span.fs24
                  = money_to_text(@cart.products_total_price)
                  '
                  'руб.

              - if !@cart.products_discount.zero?
                .fs14
                  | Ваша скидка:
                  '
                  = money_to_text(@cart.products_discount)
                  '
                  'руб.


          .ptz_tr
            .ptz_td
              .fs15.mt30.mb30
                - if @cart.delivery.moderation_required?
                  b>
                    | [Итоговую сумму с учетом доставки уточнит оператор]
                - else
                  | Итого:
                  '
                  span.fs24= money_to_text(@cart.total_price)
                  '
                  'руб.

          .ptz_tr
            .ptz_td.tac
              .mt20
                - if @cart.active?
                  = link_to 'Оформить заказ', orders_path(cart_id: @cart), method: :post, class: 'ptz_btn ptz_size-22 ptz_style-0--btn app--btn-1'
                - else
                  .ptz_btn.ptz_size-22 Корзина Просрочена

  .w900.ma.mb20.clearfix
    .pull-right
      = link_to reset_cart_path, method: :delete, data: { confirm: "Вы действительно хотите полностью очистить корзину?" }, class: 'ptz_btn ptz_size-14' do
        i.fa.fa-ban.ptz_btn--icon
        | Начать новую корзину