config/routes.rb
module RailsShop
  # ::RailsShop::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::RailsShop::DefaultRoutes
      mapper.send :rails_shop_routes
    end
  end

  module DefaultRoutes
    def rails_shop_routes
      get 'shop_search' => "shop_search#shop_search"

      get 'products_search_a/:term' => "shop_search#ts_products_search"
      get 'products_search_b/:term' => "shop_search#psql_products_search"
      get 'products_search_c/:term' => "shop_search#psql_products_search2"

      get '/shop'       => 'products#index', as: :shop
      get 'shop/manage' => 'shop#manage',    as: :shop_manage

      get   'yandex_market/index'      => 'yandex_market#index',  as: :yandex_market
      patch 'yandex_market/switch/:id' => 'yandex_market#switch', as: :yandex_market_switch

      get   'yandex_market/export' => 'yandex_market#export', as: :yandex_market_export
      get   'yandex_market/export_this/:id' => 'yandex_market#export_this', as: :yandex_market_export_this

      resources :shop_params_cards

      resources :shop_categories do
        member do
          get :ordering
        end

        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_brands do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_colors do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_unit_ports do
        collection do
          get  :manage
          post :rebuild
        end
      end

      get "shop_ordering/:category_type/:category_id",
        action: :ordering,
        controller: :shop_category_rels,
        as: :shop_ordering

      resources :shop_category_rels do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :products do
        member do
          post  :clone
          patch :realtion_category
        end

        collection do
          get :manage
        end
      end

      # ADD/REMOVE PRODUCTS
      post   "add_to_cart/:product_id"      => "carts#add_product",    as: :add_to_cart
      delete "remove_from_cart/:product_id" => "carts#remove_product", as: :remove_from_cart

      resources :carts do
        member do
          delete :reset
          patch :set_delivery_type

          patch  :amount_decrement
          patch  :amount_increment
        end

        collection do
          get :manage
        end
      end

      resources :orders do
        member do
          get :payment_system
          get :login_before
          get :attach_current_user_to

          patch :recalc_price
          patch :completion
          get   :payment
        end

        collection do
          get :my
          get :search
          get :manage

          post :one_click
        end
      end

      resources :currency_rates do
        collection do
          get :cbr_get_rate
          get :manage
        end
      end

      resources :delivery_types do
        collection do
          get :manage
        end
      end

      # Yandex Kassa routes
      match 'payments/yk/check-url' => 'payments#yk_check',   via: %w[ get post ]
      match 'payments/yk/aviso-url' => 'payments#yk_aviso',   via: %w[ get post ]
      match 'payments/yk/success'   => 'payments#yk_success', via: %w[ get post ]
      match 'payments/yk/failure'   => 'payments#yk_failure', via: %w[ get post ]

      # Alfa Bank routes
      post 'alfa_payments' => 'payments#alfa_before'
      get  'alfa_callback' => 'payments#alfa_callback'
      get  'alfa_success'  => 'payments#alfa_success'
      get  'alfa_failure'  => 'payments#alfa_failure'

      ##########################
      # ~ SHOP
      ##########################
    end
  end
end

app/models/concerns/rails_shop/category_model.rb
module RailsShop
  module CategoryModel
    extend ActiveSupport::Concern

    included do
      include ::SimpleSort::Base
      include ::Pagination::Base
      include ::Notifications::LocalizedErrors

      include ::AttachedImages::ItemModel
      include ::RailsShop::StatesProcessing
      include ::RailsShop::ContentProcessing

      include ::TheSortableTree::Scopes
      acts_as_nested_set scope: %w[ user_id ]

      scope :in_stock, ->{ where('amount > 0') }

      validates :title, uniqueness: true
      validates_presence_of :user, :title
      validates_presence_of :slug, if: ->{ errors.blank? }

      include ::FriendlyIdPack::Base

      paginates_per 24

      belongs_to :user

      has_many :shop_category_rels, as: :category

      has_many :products,
        through: :shop_category_rels,
        source: :item, source_type: :Product

    end # included
  end
end

app/models/concerns/rails_shop/central_bank_of_russia.rb
# central bank api: http://www.cbr.ru/scripts/Root.asp?PrtId=SXML

require 'net/http'
require 'nokogiri'

# include ::RailsShop::CentralBankOfRussia
module RailsShop
  module CentralBankOfRussia
    def cbr_eur_code; 'R01239'; end
    def cbr_usd_code; 'R01235'; end

    def cbr_daily_rates_url
      'http://www.cbr.ru/scripts/XML_daily.asp'
    end

    def cbr_range_rates_url
      'http://www.cbr.ru/scripts/XML_dynamic.asp'
    end

    def cbr_get_daily_report(date = "12/12/2012")
      @cbr_response ||= cbr_get_response(cbr_daily_rates_url, { date_req: date })
    end

    def cbr_current_eur_rate(date)
      report = cbr_get_daily_report(date)

      ::Nokogiri::XML(report.body)
        .search("Valute[ID=#{ cbr_eur_code }]")
        .children()
        .search('Value')
        .text()
        .gsub(',','.')
        .to_f
    end

    def get_cbr_current_rates
      date = Time.zone.now.strftime('%d/%m/%Y')
      self.rur_eur = cbr_current_eur_rate(date)
      self.rur_usd = cbr_current_usd_rate(date)
    end

    def cbr_current_usd_rate(date)
      report = cbr_get_daily_report(date)

      Nokogiri::XML(report.body)
        .search("Valute[ID=#{ cbr_usd_code }]")
        .children()
        .search('Value')
        .text()
        .gsub(',','.')
        .to_f
    end

    def cbr_get_response(url, params = {})
      uri       = URI(url)
      uri.query = URI.encode_www_form(params)
      Net::HTTP.get_response(uri)
    end

  end
end

# http://opensourceconnections.com/blog/2008/04/24/adding-timeout-to-nethttp-get_response/
# rescue Errno::EHOSTUNREACH, Errno::ENETUNREACH
# retry

# def cbr_get_range_report(date_from, date_to, currency_code)
#   params = {
#     date_req1: date_from,
#     date_req2: date_to,
#     :'VAL_NM_RQ' => currency_code
#   }
#   cbr_get_response(cbr_range_rates_url, params)
# end

app/models/concerns/rails_shop/content_processing.rb
# include ::RailsShop::ContentProcessing
module RailsShop
  module ContentProcessing
    def content_processing_for current_user
      return unless current_user

      self.title   = title.squish.strip
      self.intro   = process_content(raw_intro,   current_user)
      self.content = process_content(raw_content, current_user)
    end

    def process_content txt, current_user
      al_helper = ::AutoLink.new

      txt = sanitize_for(txt, current_user)
      txt = txt.empty_p2br

      txt = al_helper.auto_link(txt, sanitize: false, html: { target: :_blank, rel: :nofollow })
      txt = txt.add_nofollow_to_links if !current_user.admin?
      txt = txt.wrap_nofollow_links_with_noindex

      txt.strip
    end

    def sanitize_for txt, current_user
      if current_user.admin?
        ::Sanitize.fragment(txt, Sanitize::Config::ADMIN_RELAXED)
      else
        ::Sanitize.fragment(txt, Sanitize::Config::BLOGGER_HTML)
      end
    end

  end
end

app/models/concerns/rails_shop/price_methods.rb
# include ::RailsShop::PriceMethods
module RailsShop
  module PriceMethods

    def products_total_price
      products.inject(0){|res, cart_item| res += (cart_item.amount * cart_item.item.discounted_price.to_f) }
    end

    def delivery_total_price
      delivery.try(:price) || 0
    end

    def total_price
      products_total_price - products_discount + delivery_total_price
    end

    def products
      items_relation.products
    end

    def delivery
      items_relation.deliveries.first.try(:item)
    end

    def products_discount
      return 0

      return 0 unless user

      base_price = products_total_price

      if user.orders.paid.count > 0
        (base_price / 100.0)*2
      else
        (base_price / 100.0)*1
      end
    end
  end # PriceMethods
end # RailsShop

app/models/concerns/rails_shop/user.rb
# include ::RailsShop::User
module RailsShop
  module User
    extend ActiveSupport::Concern

    included do
      has_many :products
      has_many :shop_categories
      has_many :shop_brands
      has_many :delivery_types
      has_many :carts

      # def actual_email
      #   return '' if email.match(/open-cook.ru/mix)
      #   email
      # end
    end # included

    def rails_shop_admin?
      self.admin?
    end
  end # User
end # RailsShop

app/controllers/concerns/rails_shop/alfa_bank_payments.rb
require 'net/http'

# TEST TEST
# 4111 1111 1111 1111
# 2019/12
# 123
# 3dsecure: 12345678

# Регистрация заказа  https://pay.alfabank.ru/payment/rest/register.do
# Регистрация заказа с предавторизацией   https://pay.alfabank.ru/payment/rest/registerPreAuth.do
# Запрос завершения оплаты заказа   https://pay.alfabank.ru/payment/rest/deposit.do
# Запрос отмены оплаты заказа   https://pay.alfabank.ru/payment/rest/reverse.do
# Запрос возврата средств оплаты заказа   https://pay.alfabank.ru/payment/rest/refund.do
# Получение статуса заказа  https://pay.alfabank.ru/payment/rest/getOrderStatus.do
# Получение расширенного статуса заказа   https://pay.alfabank.ru/payment/rest/getOrderStatusExtended.do
# Запрос проверки вовлеченности карты в 3DS     https://pay.alfabank.ru/payment/rest/verifyEnrollment.do
# Запрос статистики по платежам за период   https://pay.alfabank.ru/payment/rest/getLastOrdersForMerchants.do

# Название метода   URL WSDL
# Описание WebService (WSDL)  https://pay.alfabank.ru/payment/webservices/merchant-ws?wsdl

# Название метода   URL
# Личный кабинет  https://pay.alfabank.ru/mportal

# include RailsShop::AlfaBankPayments
module RailsShop
  module AlfaBankPayments
    extend ActiveSupport::Concern

    ALFA_GATEWAY_URL = Settings.rails_shop.alfa_payments.api.url      # https://pay.alfabank.ru/payment/rest/
    ALFA_RETURN_URL  = Settings.rails_shop.alfa_payments.api.callback # https://example.com/alfa_callback

    ALFA_API_USER = Settings.rails_shop.alfa_payments.api.login
    ALFA_API_PASS = Settings.rails_shop.alfa_payments.api.password

    ALFA_AUTH_DATA = { userName: ALFA_API_USER, password: ALFA_API_PASS }

    included do
      SHOP_PUBLIC_ACTIONS = %w[ alfa_before alfa_callback alfa_success alfa_failure ]
      layout 'rails_shop_frontend'

      skip_before_action :authenticate_user!,        only: SHOP_PUBLIC_ACTIONS
      skip_before_action :shop_admin_required!,      only: SHOP_PUBLIC_ACTIONS
      skip_before_action :verify_authenticity_token, only: SHOP_PUBLIC_ACTIONS
    end

    def alfa_before
      order_id = params[:orderNumber]
      price = (params[:sum].to_f * 100).to_i

      unless order_ready_check(order_id)
        redirect_to alfa_failure_path(id: order_id)
      end

      data = {
        amount: price,
        orderNumber: order_id,
        returnUrl: ALFA_RETURN_URL
      }

      res = alfa_gateway('register.do', data)

      begin
        AlfaLogMailer.log_params("Alfa Bank PrePay: #{ order_id }", {
          order: order_id,
          alfa_price: price,
          price_param: params[:sum],

          response: res,
          params: params,
          ssl: request.ssl?,
        }).deliver_now
      rescue; end

      if (alfa_bank_payment_page = res['formUrl']).present?
        redirect_to alfa_bank_payment_page
      else
        redirect_to alfa_failure_path(id: order_id)
      end
    end

    def alfa_callback
      # /alfa_callback?orderId=29742882-196c-4ef2-9517-4859f6933e41
      alfa_order_id = params[:orderId]
      data = { orderId: alfa_order_id }
      res = alfa_gateway('getOrderStatus.do', data)

      begin
        AlfaLogMailer.log_params("Alfa Bank Callback", {
          alfa_order_id: alfa_order_id,
          response: res,
          params: params,
          ssl:    request.ssl?
        }).deliver_now
      rescue; end

      if res['ErrorCode'] == '0'
        order_id = res['OrderNumber']

        @order = Order.where(uid: order_id).first
        @order.process_payment_complete!

        begin
          AlfaLogMailer.log_params("Alfa Bank - ЗАКАЗ ОПЛАЧЕН", {
            alfa_order_id: alfa_order_id,
            response: res,
            params: params,
            ssl:    request.ssl?
          }).deliver_now
        rescue; end

        redirect_to alfa_success_url(id: order_id)
      else

        begin
          AlfaLogMailer.log_params("Alfa Bank - ОШИБКА ОПЛАТЫ ЗАКАЗА", {
            alfa_order_id: alfa_order_id,
            response: res,
            params: params,
            ssl:    request.ssl?
          }).deliver_now
        rescue; end

        redirect_to alfa_failure_path(id: order_id)
      end
    end

    def alfa_success
      order_uid = params[:id].to_s.downcase
      @order = Order.where(uid: order_uid).first
    end

    def alfa_failure
      order_uid = params[:id].to_s.downcase
      @order = Order.where(uid: order_uid).first
    end

    private

    def order_ready_check order_number
      Order.where(uid: order_number).first.ready_for_sale?
    end

    def alfa_gateway(action, params = {})
      params = params.merge(ALFA_AUTH_DATA)
      uri = URI(ALFA_GATEWAY_URL + action)
      res = ::Net::HTTP.post_form(uri, params)
      JSON.parse(res.body)
    end
  end
end

app/controllers/concerns/rails_shop/category_common_controller.rb
# include RailsShop::MainImageActions
module RailsShop
  module CategoryCommonController
    extend ActiveSupport::Concern

    included do
      before_action :set_shop_category, only: %w[ show ]
      before_action :set_editable_shop_category, only: %w[ edit update destroy ]

      include ::TheSortableTreeController::Rebuild
    end # included

    def index
      # ???
    end

    def show
      @shop_category_rels =
        ::ShopCategoryRel.base_scope
          .where(category: @shop_category)

      @filter_types = @shop_category_rels
        .pluck(:item_shop_params_card_type)
        .uniq
        .compact

      @shop_category_rels =
        @shop_category_rels
          .includes(:item)
          .show_sorting(params)
          .pagination(params)

      @shop_items = @shop_category_rels.map(&:item)
      render category_template(:show)
    end

    # RESTRICTED AREA

    def manage
      @shop_categories = category_klass.for_manage.nested_set
      render category_template(:manage)
    end

    def new
      @shop_category = category_klass.new
      render category_template(:new)
    end

    def edit
      render category_template(:edit)
    end

    def create
      @shop_category = current_user.send(category_name).new(shop_category_params)

      if @shop_category.save
        redirect_to url_for([:edit, @shop_category]), notice: 'Категория успешно создан'
      else
        render category_template(:new)
      end
    end

    def update
      @shop_category.assign_attributes(shop_category_params)
      @shop_category.content_processing_for(current_user)

      if @shop_category.save
        redirect_to url_for([:edit, @shop_category]), notice: 'Категоря успешно обновлена'
      else
        render category_template(:edit)
      end
    end

    def destroy
      @shop_category.destroy
      redirect_to [:manage, @shop_category], notice: 'Раздел удален'
    end

    private

    def set_shop_category
      @shop_category = category_klass.available_for(current_user).friendly_first(params[:id])
      return page_404 unless @shop_category
    end

    def set_editable_shop_category
      @shop_category = category_klass.for_manage.friendly_first(params[:id])
      return page_404 unless @shop_category
    end

    def shop_category_params
      param_name = category_name.singularize

      params.require(param_name).permit(
        :title,
        :url,
        :raw_intro,
        :raw_content,
        :state
      )
    end

    def category_name
      category_klass.name.tableize
    end

    def category_template name
      { template: "rails_shop/#{ category_name }/#{ name }" }
    end
  end
end

app/controllers/concerns/rails_shop/main_image_actions.rb
# include RailsShop::MainImageActions
module RailsShop
  module MainImageActions

    ACTIONS = %w[
      main_image_crop_16x9
      main_image_crop_4x3
      main_image_crop_1x1
      main_image_rotate_left
      main_image_rotate_right
      main_image_delete
    ]

    def main_image_crop_16x9
      path = @main_image_holder.main_image_crop_16x9(params)
      render json: { ids: { '@main-image--v16x9' => path + rnd_num  } }
    end

    def main_image_crop_4x3
      path = @main_image_holder.main_image_crop_4x3(params)
      render json: { ids: { '@main-image--v4x3' => path + rnd_num } }
    end

    def main_image_crop_1x1
      path = @main_image_holder.main_image_crop_1x1(params)
      render json: { ids: { '@main-image--v1x1' => path + rnd_num } }
    end

    def main_image_rotate_left
      @main_image_holder.main_image_rotate_left
      redirect_to :back
    end

    def main_image_rotate_right
      @main_image_holder.main_image_rotate_right
      redirect_to :back
    end

    def main_image_delete
      @main_image_holder.main_image_destroy!
      redirect_to :back
    end

    private

    def rnd_num
      "?#{ Time.now.to_i }"
    end

  end # MainImageActions
end # RailsShop

app/views/rails_shop/orders/_order_without_login.html.slim
- intro_visible   = 'display:none' if  visible
- content_visible = 'display:none' if !visible
- gray_style = 'form-classic--lightgray-theme' if !visible

.ptz_div-0.p20@registration-accordion(class=gray_style)
  @registration-accordion--intro(style=intro_visible)

    @registration-accordion--switcher
      input#accounted-off-always.radio-btn(type='checkbox' autocomplete='off')
      label(for='accounted-off')
        span.fs16 Оформить заказ без регистрации

  @registration-accordion--content(style=content_visible)
    .ptz_table.w100p
      .ptz_tr
        .ptz_td.pl10
          p.mt0 Я хочу просто закончить оформление заказа:
          = link_to 'Оформить заказ', @order, class: 'ptz_btn ptz_size-18 ptz_style-0--btn'

  / .cell.pl0.pt10.pr10.w40
  /   input#accounted-on-always.radio-btn(type='checkbox' checked='checked' autocomplete='off')
  /   label(for='accounted-on')

app/views/rails_shop/orders/index.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- content_for :left_sidebar do
  = render partial: 'users/left_sidebar'

table.table-light--table.w100p
  tr.table-light--tr
    th.table-light--th.fs15 Номер заказа
    th.table-light--th.fs15= link_to 'Кол-во ↕', simple_sort_url(:order_items_counter)

    th.table-light--th.fs15 Товары

    th.table-light--th.fs15= link_to 'Статус ↕', simple_sort_url(:state)
    th.table-light--th.fs15= link_to 'Цена ↕', simple_sort_url(:total_price)

    th.table-light--th.fs15= link_to 'Дата создания ↕', simple_sort_url(:created_at)

  - @orders.each do |order|
    tr.table-light--tr
      td.table-light--td.vam
        = link_to order.uid.upcase, order, class: 'link--block fs15 pt0 lh120'

      td.table-light--td.vam
        .fs15.pt0.lh120 = order.order_items_counter

      td.table-light--td.vam.w100p
        .fs15
          - order.products.each do |product|
            - product = product.item

            = image_tag product.main_image_url(:v100x100), width: '30', title: product.title
      td.table-light--td.vam
        .fs15.br-off= t order.state, scope: %w[ rails_shop orders state ]
      td.table-light--td.vam
        .fs15
          span.ml10(title='Полная цена')= money_to_text order.total_price

      td.table-light--td.vam
        .fs15= order.created_at.strftime('%d.%m.%Y %H:%M')

= render template: 'common/paginator', locals: { items: @orders }

app/views/rails_shop/orders/login_before.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

h3.mt20.mb10.fs20 Оформить заказ без регистрации

.ptz_theme-0
  .mb50= render partial: 'rails_shop/orders/order_without_login', locals: { visible: true }

h3.mt20.mb10.fs20 Зарегистрироваться на сайте

= render partial: 'notifications/flash', locals: { format: :json }

- callback_path = attach_current_user_to_order_path(@order)

.mt20.mb20= render partial: 'devise/sessions/social_login',       locals: { visible: false, callback_path: callback_path }
.mt20.mb20= render partial: 'devise/sessions/email_singup',       locals: { visible: false, callback_path: callback_path }
.mt20.mb20= render partial: 'devise/sessions/email_login',        locals: { visible: false, callback_path: callback_path }
.mt20.mb20= render partial: 'devise/sessions/onetime_login_link', locals: { visible: false, callback_path: callback_path }

app/views/rails_shop/orders/manage.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- content_for :left_sidebar do
  .m20= render partial: 'users/left_sidebar'

.ptz_theme-0.m20
  .mt20.mb20.fs14
    span.mr15= link_to 'Кабинет', cabinet_path
    span.mr15 &raquo;
    span.mr15= link_to 'Управлять заказами', manage_orders_path

  table.ptz_table-0.w100p
    thead
      tr
        th.p10.fs15.br-off
          = link_to 'ID ↕', simple_sort_url(:id)
        th.p10.fs15.br-off Номер заказа
        th.p10.fs15.br-off= link_to 'Кол-во ↕', simple_sort_url(:order_items_counter)

        th.p10.fs15.br-off.tal Товары

        th.p10.fs15.br-off= link_to 'Статус ↕', simple_sort_url(:state)
        th.p10.fs15.br-off= link_to 'Цена ↕', simple_sort_url(:total_price)

        th.p10.fs15.br-off= link_to 'Дата создания ↕', simple_sort_url(:created_at)
        th.p10
          i.fs14.fa.fa-pencil
        th.p10
          i.fs14.fa.fa-trash

    tbody
      - @orders.each do |order|
        tr
          td.p10.fs18.vam.upcase
            = order.id
          td.p10.vam.br-off
            = link_to string_in_groups_by(order.uid), order, class: 'link--block fs15 pt0 lh120'

          td.p10.vam
            .fs15.pt0.lh120 = order.order_items_counter

          td.p10.vam.w100p
            .fs15
              - order.products.each do |product|
                - product = product.item
                = image_tag product.main_image_url(:v100x100), width: '30', title: product.title
          td.p10.vam
            .fs15.br-off= t order.state, scope: %w[ rails_shop orders state ]
          td.p10.vam.br-off
            .fs15
              span.ml10(title='Полная цена')= money_to_text order.total_price
              span.ml10 |
              span.ml10(title='Цена товаров')= money_to_text order.products_price
              span.ml10 |
              span.ml10(title='Цена доставки')= money_to_text order.delivery_price
              span.ml10 |
              span.ml10(title='Скидка')= money_to_text order.discount

          td.p10.vam.br-off
            .fs15= order.created_at.strftime('%d.%m.%Y %H:%M')
          th.p10.vam
            = link_to [:edit, order] do
              i.fs14.fa.fa-pencil
          th.p10.vam
            = link_to order, method: :delete, data: { confirm: 'Удалить заказ?' } do
              i.fs14.fa.fa-trash

  = render template: 'common/paginator', locals: { items: @orders }

app/views/rails_shop/orders/payment.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- @main_content_block_class = 'shop-cart--background'

.order-process-steps.mt20.mb30
  .order-process-steps--item 1. Корзина
  .order-process-steps--item 2. Доставка
  .order-process-steps--item.current 3. Оплата

.fs14.tac Проверьте данные заказа и нажмите кнопку ОПЛАТИТЬ

.w800.ma.shop-cart--list

  .ml20.mr20
    h3.fs24.mb10 Заказ: #{ @order.uid.upcase }
    .fs12.mb20 По этому номеру вы сможете найти свой заказ и отследить его статус

  hr

  .m20

    .tac.mt30
      - shop_payment_url = Settings.rails_shop.yandex_kassa.payment_url
      - shop_shop_id     = Settings.rails_shop.yandex_kassa.shop_id
      - shop_scid        = Settings.rails_shop.yandex_kassa.scid
      - shop_currancy    = Settings.rails_shop.yandex_kassa.currancy

      = form_tag shop_payment_url, data: { role: 'order-payment-form', 'payment-system-url' => payment_system_order_path(@order) } do

        ruby:
          payment_description = {
            yadengi: 'Оплата системой Яндекс.Деньги (Яндекс.Кошелек)',
            card: 'Оплата банковскими картами MASTER CARD и VISA',
            sberbank: 'Оплата через банк-клиент Сбербанка',
            web_money: 'Оплата электронными деньгами WebMoney',
            alfa_bank: 'Оплата через банк-клиент Альфа-Банка',
            promsvyaz_bank: 'Оплата через банк-клиент ПромСвязьБанка',
            qiwi: 'Оплата через платежную систему QIWI Wallet',
            euroset: 'Оплата через салоны ЕВРОСЕТЬ',
            svyaznoy: 'Оплата через салоны СВЯЗНОЙ'
          }

        .payment-systems--list
          .fs20.mb15 Выберите удобный способ оплаты:
          - Order.ps_name_id.each_pair do |type, value|
            .payment-systems--item
              input type="radio" name="paymentType" value=value id="payment_type_#{ type }" class='payment-systems--input' data={ 'role' => 'payment-type-option', 'payment-description' => payment_description[type] }
              label(for="payment_type_#{ type }", class="payment-systems--label payment-systems--#{ type }") = value

        .tal.hidden
          .mb5
            .b ShopId:
            '
            = text_field_tag :shopId, shop_shop_id, class: :input
          .mb5
            .b SCID:
            '
            = text_field_tag :scid, shop_scid, class: :input
          .mb5
            .b SUM:
            '
            = text_field_tag :sum, money_round(@order.total_price), class: :input

          .mb5
            .b Customer Number:
            '
            = text_field_tag :customerNumber, @order.uid, class: :input

          .mb5
            .b Order Number:
            '
            = text_field_tag :orderNumber, @order.uid, class: :input

        .tac.fs14.mb20@payment-type-description
          | Необходимо выбрать способ оплаты
        .tac

        - if !@order.paid?
          - money = money_to_text(@order.total_price)
          = submit_tag raw("ОПЛАТИТЬ #{ money } руб."), class: 'ptz_btn ptz_size-22 ptz_style-0--btn', disabled: :disabled, data: { role: 'order-payment-button' }
        - else
          .ptz_btn.ptz_size-22 Заказ уже оплачен

  hr.mt30

  .m20
    h3.fs20 Ваши товары

    .clearfix.mb30
      - @order.order_items.products.each do |cart_item|
        - product = cart_item.item

        .pull-left.m10
          - img = product.main_image_url(:v100x100)
          .shop-cart--image.mb5(style="background-image:url(#{ img }); width:90px;height:90px;" title=product.title)

          .fs16.tac
            |x
            = cart_item.amount

  hr

    .fs15.mt10.mb10.ml20.mr20
      - products_items = @order.order_items.where(item_type: :Product)
      - products_count = products_items.count
      - positions_plur = t(:positions_count_text, scope: %w[ rails_shop ], count: products_count)
      | #{ products_count } #{ positions_plur } на
      '
      span.fs24
        - products_total = products_items.inject(0){|res, pr| res += (pr.amount * pr.item.discounted_price.to_f) }
        = money_to_text(products_total)
        '
        'руб.

  hr

  .cart-delivery-info
    .fs18.ml5.lh130
      = @order.delivery.intro
      |:
      '
      span.b
        = money_to_text @order.delivery.price
        '
        | руб.

  .mt20.ml20.mr20
    .form-classic.mb0
      h3.fs24.mb25 Данные для доставки:

      .fs16.mb15.lh130
        span.b Получатель:
        '
        = @order.full_name

      .fs16.mb15.lh150
        span.b Адрес:
        '
        = [ @order.postcode, @order.country, @order.region, @order.city, @order.street, @order.house_number ].delete_if{|i| i.blank?}.join ', '

      .fs16.mb15.lh140
        .mb15.i Контакты:

        - if @order.phone.present?
          .mb15
            '
            | Тел.:
            '
            span.b= @order.phone

        - if @order.email.present?
          .mb15
            '
            | E-MAIL:
            '
            span.b= @order.email

      - if @order.delivery_comment.present?
        .fs16.mb10.lh120
          span.b Дополнительная информация:
          '
          = @order.delivery_comment