config/routes.rb
module RailsShop
  # ::RailsShop::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::RailsShop::DefaultRoutes
      mapper.send :rails_shop_routes
    end
  end

  module DefaultRoutes
    def rails_shop_routes
      get 'shop_search' => "shop_search#shop_search"

      get 'products_search_a/:term' => "shop_search#ts_products_search"
      get 'products_search_b/:term' => "shop_search#psql_products_search"
      get 'products_search_c/:term' => "shop_search#psql_products_search2"

      get '/shop'       => 'products#index', as: :shop
      get 'shop/manage' => 'shop#manage',    as: :shop_manage

      get   'yandex_market/index'      => 'yandex_market#index',  as: :yandex_market
      patch 'yandex_market/switch/:id' => 'yandex_market#switch', as: :yandex_market_switch

      get   'yandex_market/export' => 'yandex_market#export', as: :yandex_market_export
      get   'yandex_market/export_this/:id' => 'yandex_market#export_this', as: :yandex_market_export_this

      resources :shop_params_cards

      resources :shop_categories do
        member do
          get :ordering
        end

        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_brands do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_colors do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :shop_unit_ports do
        collection do
          get  :manage
          post :rebuild
        end
      end

      get "shop_ordering/:category_type/:category_id",
        action: :ordering,
        controller: :shop_category_rels,
        as: :shop_ordering

      resources :shop_category_rels do
        collection do
          get  :manage
          post :rebuild
        end
      end

      resources :products do
        member do
          post  :clone
          patch :realtion_category
        end

        collection do
          get :manage
        end
      end

      # ADD/REMOVE PRODUCTS
      post   "add_to_cart/:product_id"      => "carts#add_product",    as: :add_to_cart
      delete "remove_from_cart/:product_id" => "carts#remove_product", as: :remove_from_cart

      resources :carts do
        member do
          delete :reset
          patch :set_delivery_type

          patch  :amount_decrement
          patch  :amount_increment
        end

        collection do
          get :manage
        end
      end

      resources :orders do
        member do
          get :payment_system
          get :login_before
          get :attach_current_user_to

          patch :recalc_price
          patch :completion
          get   :payment
        end

        collection do
          get :my
          get :search
          get :manage

          post :one_click
        end
      end

      resources :currency_rates do
        collection do
          get :cbr_get_rate
          get :manage
        end
      end

      resources :delivery_types do
        collection do
          get :manage
        end
      end

      # Yandex Kassa routes
      match 'payments/yk/check-url' => 'payments#yk_check',   via: %w[ get post ]
      match 'payments/yk/aviso-url' => 'payments#yk_aviso',   via: %w[ get post ]
      match 'payments/yk/success'   => 'payments#yk_success', via: %w[ get post ]
      match 'payments/yk/failure'   => 'payments#yk_failure', via: %w[ get post ]

      # Alfa Bank routes
      post 'alfa_payments' => 'payments#alfa_before'
      get  'alfa_callback' => 'payments#alfa_callback'
      get  'alfa_success'  => 'payments#alfa_success'
      get  'alfa_failure'  => 'payments#alfa_failure'

      ##########################
      # ~ SHOP
      ##########################
    end
  end
end

app/models/concerns/rails_shop/category_model.rb
module RailsShop
  module CategoryModel
    extend ActiveSupport::Concern

    included do
      include ::SimpleSort::Base
      include ::Pagination::Base
      include ::Notifications::LocalizedErrors

      include ::AttachedImages::ItemModel
      include ::RailsShop::StatesProcessing
      include ::RailsShop::ContentProcessing

      include ::TheSortableTree::Scopes
      acts_as_nested_set scope: %w[ user_id ]

      scope :in_stock, ->{ where('amount > 0') }

      validates :title, uniqueness: true
      validates_presence_of :user, :title
      validates_presence_of :slug, if: ->{ errors.blank? }

      include ::FriendlyIdPack::Base

      paginates_per 24

      belongs_to :user

      has_many :shop_category_rels, as: :category

      has_many :products,
        through: :shop_category_rels,
        source: :item, source_type: :Product

    end # included
  end
end

app/models/concerns/rails_shop/central_bank_of_russia.rb
# central bank api: http://www.cbr.ru/scripts/Root.asp?PrtId=SXML

require 'net/http'
require 'nokogiri'

# include ::RailsShop::CentralBankOfRussia
module RailsShop
  module CentralBankOfRussia
    def cbr_eur_code; 'R01239'; end
    def cbr_usd_code; 'R01235'; end

    def cbr_daily_rates_url
      'http://www.cbr.ru/scripts/XML_daily.asp'
    end

    def cbr_range_rates_url
      'http://www.cbr.ru/scripts/XML_dynamic.asp'
    end

    def cbr_get_daily_report(date = "12/12/2012")
      @cbr_response ||= cbr_get_response(cbr_daily_rates_url, { date_req: date })
    end

    def cbr_current_eur_rate(date)
      report = cbr_get_daily_report(date)

      ::Nokogiri::XML(report.body)
        .search("Valute[ID=#{ cbr_eur_code }]")
        .children()
        .search('Value')
        .text()
        .gsub(',','.')
        .to_f
    end

    def get_cbr_current_rates
      date = Time.zone.now.strftime('%d/%m/%Y')
      self.rur_eur = cbr_current_eur_rate(date)
      self.rur_usd = cbr_current_usd_rate(date)
    end

    def cbr_current_usd_rate(date)
      report = cbr_get_daily_report(date)

      Nokogiri::XML(report.body)
        .search("Valute[ID=#{ cbr_usd_code }]")
        .children()
        .search('Value')
        .text()
        .gsub(',','.')
        .to_f
    end

    def cbr_get_response(url, params = {})
      uri       = URI(url)
      uri.query = URI.encode_www_form(params)
      Net::HTTP.get_response(uri)
    end

  end
end

# http://opensourceconnections.com/blog/2008/04/24/adding-timeout-to-nethttp-get_response/
# rescue Errno::EHOSTUNREACH, Errno::ENETUNREACH
# retry

# def cbr_get_range_report(date_from, date_to, currency_code)
#   params = {
#     date_req1: date_from,
#     date_req2: date_to,
#     :'VAL_NM_RQ' => currency_code
#   }
#   cbr_get_response(cbr_range_rates_url, params)
# end

app/models/concerns/rails_shop/price_methods.rb
# include ::RailsShop::PriceMethods
module RailsShop
  module PriceMethods

    def products_total_price
      products.inject(0){|res, cart_item| res += (cart_item.amount * cart_item.item.discounted_price.to_f) }
    end

    def delivery_total_price
      delivery.try(:price) || 0
    end

    def total_price
      products_total_price - products_discount + delivery_total_price
    end

    def products
      items_relation.products
    end

    def delivery
      items_relation.deliveries.first.try(:item)
    end

    def products_discount
      return 0

      return 0 unless user

      base_price = products_total_price

      if user.orders.paid.count > 0
        (base_price / 100.0)*2
      else
        (base_price / 100.0)*1
      end
    end
  end # PriceMethods
end # RailsShop

app/controllers/concerns/rails_shop/alfa_bank_payments.rb
require 'net/http'

# TEST TEST
# 4111 1111 1111 1111
# 2019/12
# 123
# 3dsecure: 12345678

# Регистрация заказа  https://pay.alfabank.ru/payment/rest/register.do
# Регистрация заказа с предавторизацией   https://pay.alfabank.ru/payment/rest/registerPreAuth.do
# Запрос завершения оплаты заказа   https://pay.alfabank.ru/payment/rest/deposit.do
# Запрос отмены оплаты заказа   https://pay.alfabank.ru/payment/rest/reverse.do
# Запрос возврата средств оплаты заказа   https://pay.alfabank.ru/payment/rest/refund.do
# Получение статуса заказа  https://pay.alfabank.ru/payment/rest/getOrderStatus.do
# Получение расширенного статуса заказа   https://pay.alfabank.ru/payment/rest/getOrderStatusExtended.do
# Запрос проверки вовлеченности карты в 3DS     https://pay.alfabank.ru/payment/rest/verifyEnrollment.do
# Запрос статистики по платежам за период   https://pay.alfabank.ru/payment/rest/getLastOrdersForMerchants.do

# Название метода   URL WSDL
# Описание WebService (WSDL)  https://pay.alfabank.ru/payment/webservices/merchant-ws?wsdl

# Название метода   URL
# Личный кабинет  https://pay.alfabank.ru/mportal

# include RailsShop::AlfaBankPayments
module RailsShop
  module AlfaBankPayments
    extend ActiveSupport::Concern

    ALFA_GATEWAY_URL = Settings.rails_shop.alfa_payments.api.url      # https://pay.alfabank.ru/payment/rest/
    ALFA_RETURN_URL  = Settings.rails_shop.alfa_payments.api.callback # https://example.com/alfa_callback

    ALFA_API_USER = Settings.rails_shop.alfa_payments.api.login
    ALFA_API_PASS = Settings.rails_shop.alfa_payments.api.password

    ALFA_AUTH_DATA = { userName: ALFA_API_USER, password: ALFA_API_PASS }

    included do
      SHOP_PUBLIC_ACTIONS = %w[ alfa_before alfa_callback alfa_success alfa_failure ]
      layout 'rails_shop_frontend'

      skip_before_action :authenticate_user!,        only: SHOP_PUBLIC_ACTIONS
      skip_before_action :shop_admin_required!,      only: SHOP_PUBLIC_ACTIONS
      skip_before_action :verify_authenticity_token, only: SHOP_PUBLIC_ACTIONS
    end

    def alfa_before
      order_id = params[:orderNumber]
      price = (params[:sum].to_f * 100).to_i

      unless order_ready_check(order_id)
        redirect_to alfa_failure_path(id: order_id)
      end

      data = {
        amount: price,
        orderNumber: order_id,
        returnUrl: ALFA_RETURN_URL
      }

      res = alfa_gateway('register.do', data)

      begin
        AlfaLogMailer.log_params("Alfa Bank PrePay: #{ order_id }", {
          order: order_id,
          alfa_price: price,
          price_param: params[:sum],

          response: res,
          params: params,
          ssl: request.ssl?,
        }).deliver_now
      rescue; end

      if (alfa_bank_payment_page = res['formUrl']).present?
        redirect_to alfa_bank_payment_page
      else
        redirect_to alfa_failure_path(id: order_id)
      end
    end

    def alfa_callback
      # /alfa_callback?orderId=29742882-196c-4ef2-9517-4859f6933e41
      alfa_order_id = params[:orderId]
      data = { orderId: alfa_order_id }
      res = alfa_gateway('getOrderStatus.do', data)

      begin
        AlfaLogMailer.log_params("Alfa Bank Callback", {
          alfa_order_id: alfa_order_id,
          response: res,
          params: params,
          ssl:    request.ssl?
        }).deliver_now
      rescue; end

      if res['ErrorCode'] == '0'
        order_id = res['OrderNumber']

        @order = Order.where(uid: order_id).first
        @order.process_payment_complete!

        begin
          AlfaLogMailer.log_params("Alfa Bank - ЗАКАЗ ОПЛАЧЕН", {
            alfa_order_id: alfa_order_id,
            response: res,
            params: params,
            ssl:    request.ssl?
          }).deliver_now
        rescue; end

        redirect_to alfa_success_url(id: order_id)
      else

        begin
          AlfaLogMailer.log_params("Alfa Bank - ОШИБКА ОПЛАТЫ ЗАКАЗА", {
            alfa_order_id: alfa_order_id,
            response: res,
            params: params,
            ssl:    request.ssl?
          }).deliver_now
        rescue; end

        redirect_to alfa_failure_path(id: order_id)
      end
    end

    def alfa_success
      order_uid = params[:id].to_s.downcase
      @order = Order.where(uid: order_uid).first
    end

    def alfa_failure
      order_uid = params[:id].to_s.downcase
      @order = Order.where(uid: order_uid).first
    end

    private

    def order_ready_check order_number
      Order.where(uid: order_number).first.ready_for_sale?
    end

    def alfa_gateway(action, params = {})
      params = params.merge(ALFA_AUTH_DATA)
      uri = URI(ALFA_GATEWAY_URL + action)
      res = ::Net::HTTP.post_form(uri, params)
      JSON.parse(res.body)
    end
  end
end

app/controllers/concerns/rails_shop/category_common_controller.rb
# include RailsShop::MainImageActions
module RailsShop
  module CategoryCommonController
    extend ActiveSupport::Concern

    included do
      before_action :set_shop_category, only: %w[ show ]
      before_action :set_editable_shop_category, only: %w[ edit update destroy ]

      include ::TheSortableTreeController::Rebuild
    end # included

    def index
      # ???
    end

    def show
      @shop_category_rels =
        ::ShopCategoryRel.base_scope
          .where(category: @shop_category)

      @filter_types = @shop_category_rels
        .pluck(:item_shop_params_card_type)
        .uniq
        .compact

      @shop_category_rels =
        @shop_category_rels
          .includes(:item)
          .show_sorting(params)
          .pagination(params)

      @shop_items = @shop_category_rels.map(&:item)
      render category_template(:show)
    end

    # RESTRICTED AREA

    def manage
      @shop_categories = category_klass.for_manage.nested_set
      render category_template(:manage)
    end

    def new
      @shop_category = category_klass.new
      render category_template(:new)
    end

    def edit
      render category_template(:edit)
    end

    def create
      @shop_category = current_user.send(category_name).new(shop_category_params)

      if @shop_category.save
        redirect_to url_for([:edit, @shop_category]), notice: 'Категория успешно создан'
      else
        render category_template(:new)
      end
    end

    def update
      @shop_category.assign_attributes(shop_category_params)
      @shop_category.content_processing_for(current_user)

      if @shop_category.save
        redirect_to url_for([:edit, @shop_category]), notice: 'Категоря успешно обновлена'
      else
        render category_template(:edit)
      end
    end

    def destroy
      @shop_category.destroy
      redirect_to [:manage, @shop_category], notice: 'Раздел удален'
    end

    private

    def set_shop_category
      @shop_category = category_klass.available_for(current_user).friendly_first(params[:id])
      return page_404 unless @shop_category
    end

    def set_editable_shop_category
      @shop_category = category_klass.for_manage.friendly_first(params[:id])
      return page_404 unless @shop_category
    end

    def shop_category_params
      param_name = category_name.singularize

      params.require(param_name).permit(
        :title,
        :url,
        :raw_intro,
        :raw_content,
        :state
      )
    end

    def category_name
      category_klass.name.tableize
    end

    def category_template name
      { template: "rails_shop/#{ category_name }/#{ name }" }
    end
  end
end

app/controllers/concerns/rails_shop/main_image_actions.rb
# include RailsShop::MainImageActions
module RailsShop
  module MainImageActions

    ACTIONS = %w[
      main_image_crop_16x9
      main_image_crop_4x3
      main_image_crop_1x1
      main_image_rotate_left
      main_image_rotate_right
      main_image_delete
    ]

    def main_image_crop_16x9
      path = @main_image_holder.main_image_crop_16x9(params)
      render json: { ids: { '@main-image--v16x9' => path + rnd_num  } }
    end

    def main_image_crop_4x3
      path = @main_image_holder.main_image_crop_4x3(params)
      render json: { ids: { '@main-image--v4x3' => path + rnd_num } }
    end

    def main_image_crop_1x1
      path = @main_image_holder.main_image_crop_1x1(params)
      render json: { ids: { '@main-image--v1x1' => path + rnd_num } }
    end

    def main_image_rotate_left
      @main_image_holder.main_image_rotate_left
      redirect_to :back
    end

    def main_image_rotate_right
      @main_image_holder.main_image_rotate_right
      redirect_to :back
    end

    def main_image_delete
      @main_image_holder.main_image_destroy!
      redirect_to :back
    end

    private

    def rnd_num
      "?#{ Time.now.to_i }"
    end

  end # MainImageActions
end # RailsShop

app/controllers/delivery_types_controller.rb
class DeliveryTypesController < RailsShopController

  before_action :set_delivery_type, only: [:show, :edit, :update, :destroy] + RailsShop::MainImageActions::ACTIONS
  before_action :set_holder_for_main_image, only: RailsShop::MainImageActions::ACTIONS

  # RESTRICTED AREA

  def manage
    @delivery_types = DeliveryType.for_manage
  end

  def new
    @delivery_type = DeliveryType.new
  end

  def create
    @delivery_type = current_user.delivery_types.new(delivery_type_params)
    @delivery_type.content_processing_for(current_user)

    if @delivery_type.save
      redirect_to url_for([:edit, @delivery_type]), notice: 'Тип доставки успешно создан'
    else
      render action: 'new'
    end
  end

  def edit; end

  def update
    @delivery_type.assign_attributes(delivery_type_params)
    @delivery_type.content_processing_for(current_user)

    if @delivery_type.save
      redirect_to url_for([:edit, @delivery_type]), notice: 'Тип доставки успешно обновлен'
    else
      render action: 'edit'
    end
  end

  private

  def set_delivery_type
    @delivery_type = DeliveryType.for_manage.find(params[:id])
  end

    def set_holder_for_main_image
      @main_image_holder = @delivery_type
    end

  def delivery_type_params
    params.require(:delivery_type).permit(
      :main_image,

      :title,
      :price,

      :raw_intro,
      :raw_content,

      :default_option,
      :order_moderation_required,

      :state,
      :delivery_kind
    )
  end
end

app/views/rails_shop/delivery_types/edit.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- content_for :left_sidebar do
  .mt20.mb20
    = link_to 'Главная', root_path, class: 'ptz_btn ptz_size-16 w100p'
  .mt20.mb20
    = link_to 'Все типы доставки', manage_delivery_types_path, class: 'ptz_btn size-16'

.ptz_theme-0.m20.w800
  h3.mt20.mb20.fs18 Редактировать тип доставки

  = render partial: 'notifications/form', locals: { object: @delivery_type }

  .ptz_div-0.w600
    = form_for @delivery_type, html: { class: 'form-classic' } do |f|
      .m20

        .mb15
          = f.label :title, 'Название', class: 'block fs13 mb5'
          = f.text_field :title, class: 'ptz_input ptz_size-15 w500 '

        .mb15.clearfix
          .pull-left.mr30
            = f.label :price, 'Цена', class: 'block fs13 mb5'
            = f.number_field :price, class: 'ptz_input ptz_size-15 w150 ', maxlength: 10, min: 0, max: 100000, placeholder: '1000', autocomplete: :off

        .mb25
          = f.label :raw_intro, 'Короткое описание типа доставки', class: 'block fs13 mb5'
          = f.text_area :raw_intro, class: 'ptz_textarea ptz_size-15 w500 form-classic--textarea'

        .mb25
          = f.label :raw_content, 'Подробное описание типа доставки', class: 'block fs13 mb5'
          = f.text_area :raw_content, rows: 7, class: 'ptz_textarea ptz_size-15 w500 form-classic--textarea'

        .mb25.clearfix
          .pull-left.w30= f.check_box :default_option, class: '', autocomplete: :off
          .pull-left.w400= f.label :default_option, 'Тип доставки по умолчанию', class: 'block fs13 mb5'


        .ptz_hr-0.mb20.mt20

        .mb25.clearfix
          = f.label :delivery_kind, 'Тип доставки', class: 'block fs13 mb5'

          .clearfix.fs12.lh120.mb15
            .pull-left.w45p.mr30
              - options = options_for_select(DeliveryType::KINDS.map{|item| [t(item, scope: %w[ rails_shop delivery_kind ]), item] }, @delivery_type.delivery_kind)
              = f.select :delivery_kind, options, {}, autocomplete: :off, class: 'ptz_input ptz_size-15 w250 form-classic--select'
            .pull-left.w40p
              | Влияет на то, какие обязательные поля адреса доставки требуется заполнить при оформлении заказа

          .clearfix.fs14.lh125
            .mb10 <b>Модерируемый</b> &mdash; Требует все базовые поля и блокирует заказ, пока модератор не проверит данные и не установит сумму доставки.
            .mb10 <b>Зарубежный</b> &mdash; Требует все базовые поля и устанавливает в качестве страны НЕ Россию (По умолчанию Беларусь)
            .mb10 <b>По стране</b> &mdash; Требует все базовые поля и устанавливает в качестве страны указана Россия
            .mb10 <b>Местный</b> &mdash; Требует только имя, телефон и комментарий
            .mb10 <b>Самовывоз</b> &mdash; Требует только имя, телефон и комментарий

        .ptz_hr-0.mb20.mt20

        .mb25.clearfix
          .pull-left.w30= f.check_box :order_moderation_required, class: '', autocomplete: :off
          .pull-left.w400= f.label :order_moderation_required, 'Позиция блокирующая оплату заказа', class: 'block fs13 mb5'

        .clearfix.fs14.lh125
          .mb10
            | Установите эту опцию если вам требуется установить тип доставки "Зарубежный", "По стране", "Местный" и вы хотите запретить оплату заказа пока модератор не проверит данные и не установит сумму доставки.

        .ptz_hr-0.mb20.mt20

        .clearfix
          = f.label :state, 'Видимость', class: 'block fs13 mb5'
          - options = options_for_select({ 'Черновик' => :draft, 'Опубликовано' => :published }, @delivery_type.state)
          = f.select :state, options, {}, autocomplete: :off, class: 'ptz_input ptz_size-15 w250 form-classic--select'

        .ptz_hr-0.mb20.mt20

        div
          = f.submit 'Обновить тип доставки', class: 'ptz_btn ptz_size-20'

app/views/rails_shop/delivery_types/manage.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- content_for :left_sidebar do
  | &nbsp;
  / = render partial: 'rails_shop/layouts/items/left_sidebar'

.m20
  h3.mt20.mb30.fs18 Редактировать типы доставки

  ol.ol.mb30
    - @delivery_types.each do |dt|
      li.fs15.mb15
        = link_to [:edit, dt], class: 'fs15' do
          span.b.mr10
            => money_round dt.price
            | руб.

          = dt.title

          - if dt.default_option
            '
            | (по умолчанию)
          - if dt.order_moderation_required
            '
            | (Блокирующая позиция)
          '
          | (#{ t dt.delivery_kind, scope: %w[ rails_shop delivery_kind ] })

  .mb25= link_to 'Новый тип доставки', new_delivery_type_url, class: 'ptz_btn ptz_size-14'

app/views/rails_shop/delivery_types/new.html.slim
= render template: 'rails_shop/layouts/items/header_footer'

- content_for :left_sidebar do
  .mt20.mb20
    = link_to 'Все типы доставки', manage_delivery_types_path, class: 'ptz_btn size-16'

.ptz_theme-0.m20
  h3.mt20.mb20.fs18 Новый тип доставки

  = render partial: 'notifications/form', locals: { object: @delivery_type, format: :json }

  .ptz_div-0.w600
    = form_for @delivery_type, html: { class: '' } do |f|
      .m20
        .mb15
          = f.label :title, 'Название', class: 'block fs13 mb5'
          = f.text_field :title, class: 'ptz_input ptz_size-15 w500'

        div
          = f.submit 'Создать тип доставки', class: 'ptz_btn ptz_size-14'